import SwiftUI
import UniformTypeIdentifiers
import RTICore

/// Read-only browser for archived session records (the Markdown folders
/// SessionArchive writes to the vault on stop). Browse and read — never
/// resume: past sessions are vault content, and anything beyond reading
/// (search, analysis, Q&A) is a vault job, not an app feature.
struct SessionsBrowserView: View {
    @State private var sessions: [SessionArchive.ArchivedSession] = []
    @State private var selected: SessionArchive.ArchivedSession?
    @State private var files: [SessionFile] = []
    @State private var selectedFile: SessionFile?
    @State private var fileText: String = ""
    @State private var upgradeStatus: String?
    @State private var upgradeStatusSessionID: URL?
    @State private var upgradingSessionID: URL?
    @State private var pendingUpgradeSession: SessionArchive.ArchivedSession?
    @State private var showingUpgradeProviderChoice = false
    @State private var showingTitleEditor = false
    @State private var titleDraft = ""
    @State private var editingSummary = false
    @State private var summaryDraft = ""
    @State private var showingSpeakerEditor = false
    @State private var speakerNames: [String: String] = [:]
    @State private var regeneratingSummaryID: URL?
    @State private var editingTranscript = false
    @State private var transcriptTurns: [SessionTranscriptTurn] = []

    struct SessionFile: Identifiable, Hashable {
        var id: URL { url }
        let url: URL
        let name: String
    }

    /// Preferred reading order when a session folder is opened.
    private static let fileOrder = ["summary.md", "live-intelligence.md", "notes.md", "transcript.md", "chat.md", "discussion-guide.md"]

    var body: some View {
        HSplitView {
            sessionList
                .frame(minWidth: 228, idealWidth: 260, maxWidth: 320)

            VStack(alignment: .leading, spacing: 0) {
                if let selected {
                    detailToolbar(for: selected)
                    if let upgradeStatus, upgradeStatusSessionID == selected.id {
                        upgradeStatusLine(upgradeStatus)
                    }
                    Divider()
                    ScrollView {
                        HStack(alignment: .top, spacing: 0) {
                            readerContent
                                .frame(maxWidth: 760, alignment: .leading)
                                .padding(.horizontal, 32)
                                .padding(.vertical, 28)
                            Spacer(minLength: 0)
                        }
                    }
                    .frame(maxWidth: .infinity)
                    .background(SessionReadingBackground())
                } else {
                    emptyState
                }
            }
            .frame(minWidth: 380)
        }
        .onAppear(perform: reload)
        .onChange(of: selected) { _, _ in
            loadFiles()
            loadSpeakerNames()
        }
        .onChange(of: selectedFile) { _, _ in loadText() }
        .onReceive(NotificationCenter.default.publisher(for: .rtiOpenSessionInBrowser)) { notif in
            guard let folder = notif.object as? String else { return }
            selectSession(folder: folder)
        }
        .sheet(isPresented: $showingTitleEditor) {
            titleEditor
        }
        .sheet(isPresented: $showingSpeakerEditor) {
            speakerEditor
        }
        .confirmationDialog(
            "Upgrade transcript with",
            isPresented: $showingUpgradeProviderChoice,
            titleVisibility: .visible,
            presenting: pendingUpgradeSession
        ) { session in
            ForEach(upgradeProviderChoices) { provider in
                Button(upgradeProviderButtonTitle(provider)) {
                    startTranscriptUpgrade(for: session, provider: provider)
                }
            }
            Button("Cancel", role: .cancel) {
                pendingUpgradeSession = nil
            }
        } message: { _ in
            Text("Soniox is the default general-purpose file transcript provider. Choose Aliyun when this archived session is Chinese-heavy and you want the upgraded transcript generated by Aliyun.")
        }
    }

    /// Deep-link target for the "summary ready" notification and the overlay's
    /// "Notes ready" control: refresh the list, select the matching session
    /// folder, and land on its summary. Re-selecting the same session still
    /// snaps the reader back to summary.md (loadFiles picks files.first).
    private func selectSession(folder: String) {
        sessions = SessionArchive.recentSessions(limit: 100)
        guard let match = sessions.first(where: { $0.url.lastPathComponent == folder }) else { return }
        selected = match
        loadFiles()
    }

    // MARK: - Session list

    private var sessionList: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Sessions")
                        .font(.system(size: 24, weight: .semibold))
                    Text("\(sessions.count) saved meeting\(sessions.count == 1 ? "" : "s")")
                        .font(.system(size: 12))
                        .foregroundStyle(RTIDesign.Color.textSecondary)
                }
                .padding(.horizontal, 18)
                .padding(.top, 20)

                ForEach(groupedSessions, id: \.label) { group in
                    VStack(alignment: .leading, spacing: 8) {
                        Text(group.label.uppercased())
                            .font(.system(size: 11, weight: .bold))
                            .tracking(0.8)
                            .foregroundStyle(RTIDesign.Color.textTertiary)
                            .padding(.horizontal, 18)
                        VStack(spacing: 5) {
                            ForEach(group.sessions) { session in
                                sessionRow(session)
                            }
                        }
                        .padding(.horizontal, 12)
                    }
                }
            }
        }
        .scrollContentBackground(.hidden)
        .background(.thinMaterial)
    }

    /// One row: AI-generated title as the primary label, the start time as a
    /// quiet secondary. No redundant clock icon — every row is a past session,
    /// so the icon was just clutter. A small dot marks sessions whose
    /// auto-summary hasn't landed yet (still "Untitled").
    private func sessionRow(_ session: SessionArchive.ArchivedSession) -> some View {
        Button {
            selected = session
        } label: {
            HStack(alignment: .center, spacing: 10) {
                RoundedRectangle(cornerRadius: 1)
                    .fill(selected == session ? RTIDesign.Color.accent : Color.clear)
                    .frame(width: 3, height: 30)

                VStack(alignment: .leading, spacing: 3) {
                    Text(session.title ?? "Untitled session")
                        .font(.system(size: 13, weight: selected == session ? .semibold : .medium))
                        .lineLimit(2)
                        .foregroundStyle(session.title == nil ? RTIDesign.Color.textSecondary : RTIDesign.Color.textPrimary)
                    HStack(spacing: 6) {
                        Text(timeString(for: session))
                            .font(.system(size: 10, design: .monospaced))
                            .foregroundStyle(RTIDesign.Color.textTertiary)
                        if session.title == nil {
                            Circle()
                                .fill(Color.secondary.opacity(0.5))
                                .frame(width: 4, height: 4)
                                .help("No summary yet — the title appears once the end-of-session summary finishes.")
                        }
                    }
                }
                Spacer(minLength: 0)
            }
            .padding(.horizontal, 10)
            .padding(.vertical, 10)
            .background(
                RoundedRectangle(cornerRadius: 11, style: .continuous)
                    .fill(selected == session ? RTIDesign.Color.cardBackground : Color.clear)
                    .shadow(
                        color: selected == session ? .black.opacity(0.05) : .clear,
                        radius: 3,
                        y: 1
                    )
            )
        }
        .buttonStyle(.plain)
    }

    // MARK: - Detail toolbar

    /// File picker (summary / notes / transcript / …) aligned with the
    /// reading column, with contextual actions trailing in the titlebar-style
    /// header.
    @ViewBuilder
    private func detailToolbar(for session: SessionArchive.ArchivedSession) -> some View {
        VStack(alignment: .leading, spacing: 13) {
            HStack(alignment: .center, spacing: 12) {
                VStack(alignment: .leading, spacing: 3) {
                    Text(session.title ?? "Untitled session")
                        .font(.system(size: 18, weight: .semibold))
                        .foregroundStyle(RTIDesign.Color.textPrimary)
                        .lineLimit(1)
                    Text(sessionDetailLine(for: session))
                        .font(.system(size: 11))
                        .foregroundStyle(RTIDesign.Color.textSecondary)
                }

                Spacer(minLength: 12)

                Menu {
                    if session.isRTIArchive {
                        Button("Edit title…") { beginTitleEdit(for: session) }
                        Button("Name speakers…") { showingSpeakerEditor = true }
                        Divider()
                    }
                    Button("Save as Markdown…") { exportMarkdown() }
                    Button("Save as PDF…") { exportPDF() }
                    Divider()
                    Button("Reveal in Finder") {
                        NSWorkspace.shared.activateFileViewerSelecting([session.url])
                    }
                } label: {
                    Image(systemName: "ellipsis")
                        .frame(width: 26, height: 26)
                }
                .menuStyle(.borderlessButton)
                .help("More session actions")
            }

            HStack(alignment: .center, spacing: 10) {
                HStack(spacing: 3) {
                    ForEach(files) { file in
                        Button {
                            selectedFile = file
                        } label: {
                            Text(displayName(for: file))
                                .font(.system(size: 12, weight: selectedFile == file ? .semibold : .medium))
                                .foregroundStyle(
                                    selectedFile == file
                                        ? RTIDesign.Color.textPrimary
                                        : RTIDesign.Color.textSecondary
                                )
                                .padding(.horizontal, 11)
                                .frame(height: 28)
                                .background(
                                    RoundedRectangle(cornerRadius: 8, style: .continuous)
                                        .fill(selectedFile == file ? RTIDesign.Color.cardBackground : Color.clear)
                                        .shadow(
                                            color: selectedFile == file ? .black.opacity(0.06) : .clear,
                                            radius: 2,
                                            y: 1
                                        )
                                )
                        }
                        .buttonStyle(.plain)
                    }
                }
                .padding(3)
                .background(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .fill(RTIDesign.Color.trackBackground)
                )
                .layoutPriority(1)

                Spacer(minLength: 0)

                Button {
                    NSPasteboard.copyMarkdownRich(fileText)
                } label: {
                    Label("Copy", systemImage: "doc.on.doc")
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
                .help("Copy as Markdown")
                .disabled(fileText.isEmpty)

                if selectedFile?.name == "summary" {
                    Button(editingSummary ? "Cancel" : "Edit") {
                        if editingSummary {
                            editingSummary = false
                        } else {
                            summaryDraft = fileText
                            editingSummary = true
                        }
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                    .disabled(fileText.isEmpty)
                    .help("Correct this saved summary")

                    if editingSummary {
                        Button("Save", action: saveSummary)
                            .buttonStyle(.borderedProminent)
                            .controlSize(.small)
                    } else {
                        Button(regeneratingSummaryID == session.id ? "Regenerating" : "Regenerate") {
                            regenerateSummary(for: session)
                        }
                        .buttonStyle(.bordered)
                        .controlSize(.small)
                        .disabled(regeneratingSummaryID != nil || !hasTranscript(session))
                        .help("Regenerate using this session's transcript and named speakers")
                    }
                }

                if selectedFile?.name == "transcript" {
                    if session.isRTIArchive {
                        Button(editingTranscript ? "Cancel" : "Edit transcript") {
                            if editingTranscript {
                                editingTranscript = false
                            } else {
                                loadTranscriptTurns()
                                editingTranscript = true
                            }
                        }
                        .buttonStyle(.bordered)
                        .controlSize(.small)
                        .disabled(fileText.isEmpty)
                        .help("Correct transcript turns and reassign speakers")

                        if editingTranscript {
                            Button("Save", action: saveTranscript)
                                .buttonStyle(.borderedProminent)
                                .controlSize(.small)
                                .disabled(transcriptTurns.isEmpty)
                        }

                        Button {
                            promptTranscriptUpgrade(for: session)
                        } label: {
                            Label(upgradingSessionID == session.id ? "Upgrading" : "Upgrade", systemImage: "waveform.badge.magnifyingglass")
                        }
                        .buttonStyle(.bordered)
                        .controlSize(.small)
                        .disabled(upgradingSessionID != nil || !canUpgrade(session))
                        .help(canUpgrade(session) ? "Run the configured async transcript provider over this session's retained audio." : "No retained session audio was found.")
                    }
                }

                Button {
                    askAboutSession(session)
                } label: {
                    Label("Ask", systemImage: "bubble.left.and.text.bubble.right")
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.small)
                .disabled(vaultRelativePath(for: session, file: "transcript.md") == nil)
                .help("Ask the overlay chat about this session's transcript.")
            }
        }
        .padding(.horizontal, 20)
        .padding(.top, 14)
        .padding(.bottom, 12)
        .background(
            Color(nsColor: .windowBackgroundColor)
                .overlay(alignment: .bottom) {
                    Rectangle()
                        .fill(RTIDesign.Color.divider)
                        .frame(height: 1)
                }
        )
    }

    @ViewBuilder
    private var readerContent: some View {
        if editingSummary {
            summaryEditor
        } else if editingTranscript {
            transcriptEditor
        } else {
            switch selectedFile?.name {
            case "transcript":
                SessionTranscriptReader(turns: SessionTranscriptReview.turns(from: fileText))
            case "live-intelligence":
                LiveIntelligenceReader(items: ArchivedFinding.parse(fileText))
            case "summary":
                if let split = summarySplit {
                    VStack(alignment: .leading, spacing: 28) {
                        SessionDocumentSection(title: "Share brief", systemImage: "paperplane") {
                            RTIMarkdown(split.brief, style: .panel)
                        }
                        Divider()
                        SessionDocumentSection(title: "Full record", systemImage: "doc.text") {
                            RTIMarkdown(split.record, style: .panel)
                        }
                    }
                } else {
                    RTIMarkdown(fileText, style: .panel)
                }
            default:
                RTIMarkdown(fileText, style: .panel)
            }
        }
    }

    private func displayName(for file: SessionFile) -> String {
        switch file.name {
        case "summary": "Summary"
        case "live-intelligence": "Intelligence"
        case "notes": "Notes"
        case "transcript": "Transcript"
        case "chat": "Chat"
        case "discussion-guide": "Guide"
        default: file.name.capitalized
        }
    }

    private func sessionDetailLine(for session: SessionArchive.ArchivedSession) -> String {
        var parts: [String] = []
        if let date = session.date {
            parts.append(Self.detailDateStamp.string(from: date))
        }
        if let duration = sessionMetadata(for: session)?.durationSeconds {
            parts.append(durationString(duration))
        }
        return parts.isEmpty ? session.displayName : parts.joined(separator: "  ·  ")
    }

    private func sessionMetadata(for session: SessionArchive.ArchivedSession) -> SessionArchiveMetadata? {
        guard session.isRTIArchive else { return nil }
        let url = session.url.appendingPathComponent("session.json")
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(SessionArchiveMetadata.self, from: data)
    }

    private func durationString(_ seconds: Int) -> String {
        let hours = seconds / 3600
        let minutes = (seconds % 3600) / 60
        let remainder = seconds % 60
        if hours > 0 {
            return "\(hours) hr \(minutes) min"
        }
        return remainder > 0 ? "\(minutes) min \(remainder) sec" : "\(minutes) min"
    }

    private static let detailDateStamp: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "MMM d, yyyy 'at' HH:mm"
        return formatter
    }()

    private func upgradeStatusLine(_ text: String) -> some View {
        HStack(spacing: 8) {
            if upgradingSessionID == upgradeStatusSessionID {
                ProgressView()
                    .controlSize(.small)
                    .scaleEffect(0.7)
            }
            Text(text)
                .font(.system(size: 11))
                .foregroundStyle(.secondary)
                .lineLimit(3)
                .fixedSize(horizontal: false, vertical: true)
            Spacer(minLength: 0)
        }
        .frame(minHeight: 28)
        .padding(.horizontal, 20)
        .padding(.vertical, 5)
        .background(.bar)
    }

    private var emptyState: some View {
        VStack(spacing: 8) {
            Image(systemName: "tray")
                .font(.system(size: 30))
                .foregroundStyle(.tertiary)
            Text(sessions.isEmpty ? "No saved sessions yet" : "Select a session")
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(.secondary)
            if !sessions.isEmpty {
                Text("Sessions appear here once they're saved on stop.")
                    .font(.system(size: 11))
                    .foregroundStyle(.tertiary)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: - Date grouping

    /// Buckets sessions into native macOS-style date sections: Today,
    /// Yesterday, This Week, then one section per older month
    /// ("June 2026"). Sessions with an unparseable folder stamp fall into
    /// "Earlier". Removes the repetitive month/day text from individual rows
    /// — the section header carries the date, the row carries just the time.
    private var groupedSessions: [(label: String, sessions: [SessionArchive.ArchivedSession])] {
        let cal = Calendar.current
        let now = Date()
        var today: [SessionArchive.ArchivedSession] = []
        var yesterday: [SessionArchive.ArchivedSession] = []
        var thisWeek: [SessionArchive.ArchivedSession] = []
        var byMonth: [(label: String, key: String, sessions: [SessionArchive.ArchivedSession])] = []
        var earlier: [SessionArchive.ArchivedSession] = []

        for session in sessions {
            guard let date = session.date else {
                earlier.append(session)
                continue
            }
            if cal.isDateInToday(date) {
                today.append(session)
            } else if cal.isDateInYesterday(date) {
                yesterday.append(session)
            } else if let days = cal.dateComponents([.day], from: date, to: now).day, days < 7 {
                thisWeek.append(session)
            } else {
                let key = monthKey(date)
                let label = monthLabel(date)
                if let idx = byMonth.firstIndex(where: { $0.key == key }) {
                    byMonth[idx].sessions.append(session)
                } else {
                    byMonth.append((label, key, [session]))
                }
            }
        }

        var out: [(label: String, sessions: [SessionArchive.ArchivedSession])] = []
        if !today.isEmpty { out.append(("Today", today)) }
        if !yesterday.isEmpty { out.append(("Yesterday", yesterday)) }
        if !thisWeek.isEmpty { out.append(("This Week", thisWeek)) }
        // Months are newest-first because `sessions` is newest-first.
        for m in byMonth.sorted(by: { $0.key > $1.key }) {
            out.append((m.label, m.sessions))
        }
        if !earlier.isEmpty { out.append(("Earlier", earlier)) }
        return out
    }

    /// "16:13" for the row's quiet secondary text. Falls back to the pretty
    /// name when the folder stamp can't be parsed.
    private func timeString(for session: SessionArchive.ArchivedSession) -> String {
        guard let date = session.date else { return session.displayName }
        return Self.rowTimeStamp.string(from: date)
    }

    private static let rowTimeStamp: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "HH:mm"
        return f
    }()

    private func monthKey(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM"
        return f.string(from: date)
    }

    private func monthLabel(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateFormat = "MMMM yyyy"
        return f.string(from: date)
    }

    // MARK: - Loading

    private func reload() {
        sessions = SessionArchive.recentSessions(limit: 100)
        if selected == nil { selected = sessions.first }
        loadSpeakerNames()
    }

    private func loadFiles() {
        guard let selected else { files = []; selectedFile = nil; return }
        guard selected.isRTIArchive else {
            files = [SessionFile(url: selected.transcriptURL, name: "transcript")]
            selectedFile = files.first
            return
        }
        let present = (try? FileManager.default.contentsOfDirectory(at: selected.url, includingPropertiesForKeys: nil)) ?? []
        let byName = Dictionary(uniqueKeysWithValues: present.map { ($0.lastPathComponent, $0) })
        files = Self.fileOrder.compactMap { name in
            byName[name].map { SessionFile(url: $0, name: String(name.dropLast(3))) }
        }
        selectedFile = files.first
    }

    private func canUpgrade(_ session: SessionArchive.ArchivedSession) -> Bool {
        session.isRTIArchive && !TranscriptUpgradeService.audioInputs(in: session.url).isEmpty
    }

    private func hasTranscript(_ session: SessionArchive.ArchivedSession) -> Bool {
        FileManager.default.fileExists(atPath: session.transcriptURL.path)
    }

    /// This session's `transcript.md` as a path relative to `databases/`, the
    /// shape the chat's `@mention` / vault tools resolve. Nil if the file is
    /// missing or the vault can't be located.
    private func vaultRelativePath(for session: SessionArchive.ArchivedSession, file: String) -> String? {
        guard let dbs = VaultWorkstreamStore.databasesDir() else { return nil }
        let fileURL = file == "transcript.md"
            ? session.transcriptURL
            : session.url.appendingPathComponent(file)
        guard FileManager.default.fileExists(atPath: fileURL.path) else { return nil }
        let base = dbs.standardizedFileURL.path
        let path = fileURL.standardizedFileURL.path
        guard path.hasPrefix(base + "/") else { return nil }
        return String(path.dropFirst(base.count + 1))
    }

    /// Bring up the overlay's Assist tab with this session's transcript
    /// pre-attached as an `@mention` so the user can ask about it — read-only,
    /// the browser itself never analyzes or answers.
    private func askAboutSession(_ session: SessionArchive.ArchivedSession) {
        guard let path = vaultRelativePath(for: session, file: "transcript.md") else { return }
        WindowCoordinator.shared.showOverlay()
        NotificationCenter.default.post(name: .rtiSelectTab, object: "assist")
        NotificationCenter.default.post(name: .rtiSeedChatMention, object: path)
    }

    private var upgradeProviderChoices: [AsyncTranscriptProviderOption] {
        let active = AsyncTranscriptProviders.active
        return [active] + AsyncTranscriptProviders.all.filter { $0.id != active.id }
    }

    private func upgradeProviderButtonTitle(_ provider: AsyncTranscriptProviderOption) -> String {
        if provider.id == AsyncTranscriptProviders.aliyun.id {
            return "Aliyun (Chinese-heavy)"
        }
        if provider.id == AsyncTranscriptProviders.soniox.id {
            return provider.id == AsyncTranscriptProviders.active.id ? "Soniox (default)" : "Soniox"
        }
        return provider.displayName
    }

    private func promptTranscriptUpgrade(for session: SessionArchive.ArchivedSession) {
        pendingUpgradeSession = session
        showingUpgradeProviderChoice = true
    }

    private func startTranscriptUpgrade(for session: SessionArchive.ArchivedSession, provider: AsyncTranscriptProviderOption) {
        pendingUpgradeSession = nil
        upgradingSessionID = session.id
        upgradeStatusSessionID = session.id
        upgradeStatus = "Starting transcript upgrade with \(provider.displayName)…"
        Task {
            do {
                let result = try await TranscriptUpgradeService.upgrade(session: session, provider: provider) { progress in
                    Task { @MainActor in
                        upgradeStatusSessionID = session.id
                        upgradeStatus = progress.message
                        if progress.isTerminal { upgradingSessionID = nil }
                    }
                }
                await MainActor.run {
                    SessionArchive.clearAutomaticUpgradePending(in: session.url)
                    upgradeStatus = result.summaryURL == nil
                        ? "Transcript upgraded with \(result.provider); summary regeneration failed."
                        : "Transcript upgraded with \(result.provider); summary regenerated."
                    upgradeStatusSessionID = session.id
                    upgradingSessionID = nil
                    reload()
                    selected = sessions.first(where: { $0.id == session.id }) ?? selected
                    loadFiles()
                    selectedFile = files.first(where: { $0.name == "transcript" }) ?? files.first
                }
            } catch {
                await MainActor.run {
                    upgradeStatus = (error as? LocalizedError)?.errorDescription ?? error.localizedDescription
                    upgradeStatusSessionID = session.id
                    upgradingSessionID = nil
                }
            }
        }
    }

    private func exportMarkdown() {
        guard let selectedFile, let selected else { return }
        let panel = NSSavePanel()
        panel.nameFieldStringValue = "rti-\(selectedFile.name)-\(selected.displayName.replacingOccurrences(of: " · ", with: "-").replacingOccurrences(of: ":", with: "")).md"
        panel.allowedContentTypes = [UTType(filenameExtension: "md") ?? .plainText]
        let content = fileText
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            try? content.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    /// Render the markdown to a paginated PDF via NSAttributedString printing.
    private func exportPDF() {
        guard let selectedFile else { return }
        let panel = NSSavePanel()
        panel.nameFieldStringValue = panelBaseName(selectedFile) + ".pdf"
        panel.allowedContentTypes = [.pdf]
        let content = fileText
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            let attributed = (try? NSAttributedString(
                markdown: content,
                options: .init(interpretedSyntax: .inlineOnlyPreservingWhitespace)
            )) ?? NSAttributedString(string: content)
            let textView = NSTextView(frame: NSRect(x: 0, y: 0, width: 540, height: 720))
            textView.textStorage?.setAttributedString(attributed)
            textView.font = .systemFont(ofSize: 11)
            let printInfo = NSPrintInfo()
            printInfo.jobDisposition = .save
            printInfo.dictionary()[NSPrintInfo.AttributeKey.jobSavingURL] = url
            printInfo.topMargin = 36; printInfo.bottomMargin = 36
            printInfo.leftMargin = 36; printInfo.rightMargin = 36
            let op = NSPrintOperation(view: textView, printInfo: printInfo)
            op.showsPrintPanel = false
            op.showsProgressPanel = false
            op.run()
        }
    }

    private func panelBaseName(_ file: SessionFile) -> String {
        let stamp = selected?.displayName
            .replacingOccurrences(of: " · ", with: "-")
            .replacingOccurrences(of: ":", with: "") ?? "session"
        return "rti-\(file.name)-\(stamp)"
    }

    private func loadText() {
        guard let selectedFile else { fileText = ""; return }
        var text = (try? String(contentsOf: selectedFile.url, encoding: .utf8)) ?? "(couldn't read file)"
        // Hide the machine-facing frontmatter block from the reading view.
        if text.hasPrefix("---"), let end = text.range(of: "\n---\n") {
            text = String(text[end.upperBound...])
        }
        fileText = applyingSpeakerNames(to: text)
    }

    private func loadTranscriptTurns() {
        guard let selectedFile, selectedFile.name == "transcript",
              let text = try? String(contentsOf: selectedFile.url, encoding: .utf8)
        else {
            transcriptTurns = []
            return
        }
        transcriptTurns = SessionTranscriptReview.turns(from: text)
    }

    private func saveTranscript() {
        guard let selectedFile, selectedFile.name == "transcript",
              let original = try? String(contentsOf: selectedFile.url, encoding: .utf8)
        else { return }
        let updated = SessionTranscriptReview.replacingTurns(in: original, with: transcriptTurns)
        try? updated.write(to: selectedFile.url, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: selectedFile.url.path)
        editingTranscript = false
        loadText()
    }

    private func loadSpeakerNames() {
        guard let selected else {
            speakerNames = [:]
            return
        }
        guard selected.isRTIArchive else {
            speakerNames = [:]
            loadText()
            return
        }
        let url = selected.url.appendingPathComponent("speaker-names.json")
        guard let data = try? Data(contentsOf: url),
              let names = try? JSONDecoder().decode([String: String].self, from: data)
        else {
            speakerNames = [:]
            return
        }
        speakerNames = names
        loadText()
    }

    private func applyingSpeakerNames(to text: String) -> String {
        speakerNames
            .filter { !$0.value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            .sorted { $0.key.count > $1.key.count }
            .reduce(text) { result, pair in
                result.replacingOccurrences(of: pair.key, with: pair.value.trimmingCharacters(in: .whitespacesAndNewlines))
            }
    }

    private var speakerLabels: [String] {
        guard let selected else { return [] }
        let transcript = selected.transcriptURL
        let text = (try? String(contentsOf: transcript, encoding: .utf8)) ?? ""
        let pattern = #"Speaker [0-9]+"#
        let range = NSRange(text.startIndex..., in: text)
        let matches = try? NSRegularExpression(pattern: pattern).matches(in: text, range: range)
        return Array(Set((matches ?? []).compactMap { match in
            Range(match.range, in: text).map { String(text[$0]) }
        })).sorted {
            Int($0.dropFirst("Speaker ".count)) ?? 0 < Int($1.dropFirst("Speaker ".count)) ?? 0
        }
    }

    private func beginTitleEdit(for session: SessionArchive.ArchivedSession) {
        titleDraft = session.title ?? ""
        showingTitleEditor = true
    }

    private func saveTitle() {
        guard let selected, selected.isRTIArchive else { return }
        let title = titleDraft.trimmingCharacters(in: .whitespacesAndNewlines)
        let url = selected.url.appendingPathComponent("title.txt")
        if title.isEmpty {
            try? FileManager.default.removeItem(at: url)
            try? FileManager.default.removeItem(at: selected.url.appendingPathComponent("title-manual.txt"))
        } else {
            try? title.write(to: url, atomically: true, encoding: .utf8)
            try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
            FileManager.default.createFile(atPath: selected.url.appendingPathComponent("title-manual.txt").path, contents: nil)
        }
        showingTitleEditor = false
        let id = selected.id
        reload()
        self.selected = sessions.first(where: { $0.id == id })
    }

    private func saveSummary() {
        guard let selectedFile, selectedFile.name == "summary" else { return }
        let original = (try? String(contentsOf: selectedFile.url, encoding: .utf8)) ?? ""
        let frontmatter: String
        if original.hasPrefix("---"), let end = original.range(of: "\n---\n") {
            frontmatter = String(original[..<end.upperBound])
        } else {
            frontmatter = ""
        }
        let content = frontmatter + summaryDraft.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
        try? content.write(to: selectedFile.url, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: selectedFile.url.path)
        editingSummary = false
        loadText()
    }

    private func regenerateSummary(for session: SessionArchive.ArchivedSession) {
        guard session.isRTIArchive else { return }
        let transcriptURL = session.transcriptURL
        guard var transcript = try? String(contentsOf: transcriptURL, encoding: .utf8) else { return }
        if transcript.hasPrefix("---"), let end = transcript.range(of: "\n---\n") {
            transcript = String(transcript[end.upperBound...])
        }
        regeneratingSummaryID = session.id
        Task {
            let summaryURL = await SessionArchive.writeAutoSummary(
                transcriptText: transcript,
                to: session.url,
                startedAt: session.date ?? Date(),
                speakerNames: speakerNames
            )
            await MainActor.run {
                regeneratingSummaryID = nil
                guard summaryURL != nil else { return }
                let id = session.id
                reload()
                selected = sessions.first(where: { $0.id == id })
                loadFiles()
            }
        }
    }

    private var titleEditor: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Edit session title")
                .font(.system(size: 18, weight: .semibold))
            Text("Use the real study or meeting name. This replaces the AI-generated label in the Sessions list.")
                .font(.system(size: 12))
                .foregroundStyle(.secondary)
            TextField("Session title", text: $titleDraft)
                .textFieldStyle(.roundedBorder)
            HStack {
                Spacer()
                Button("Cancel") { showingTitleEditor = false }
                Button("Save", action: saveTitle)
                    .keyboardShortcut(.defaultAction)
            }
        }
        .padding(22)
        .frame(width: 420)
    }

    private var summaryEditor: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("Edit summary")
                .font(.system(size: 18, weight: .semibold))
            TextEditor(text: $summaryDraft)
                .font(.system(size: 13))
                .frame(minHeight: 440)
                .overlay {
                    RoundedRectangle(cornerRadius: 7)
                        .stroke(Color.secondary.opacity(0.25))
                }
        }
    }

    private var transcriptEditor: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Edit transcript")
                .font(.system(size: 18, weight: .semibold))
            Text("Correct text or assign each turn to a named speaker. Notes stay distinct from spoken turns.")
                .font(.system(size: 12))
                .foregroundStyle(.secondary)
            ForEach($transcriptTurns) { $turn in
                VStack(alignment: .leading, spacing: 8) {
                    HStack(spacing: 8) {
                        Text(turn.timestamp)
                            .font(.system(size: 11, design: .monospaced))
                            .foregroundStyle(.secondary)
                        if turn.isNote {
                            Label("Note", systemImage: "note.text")
                                .font(.system(size: 11, weight: .medium))
                                .foregroundStyle(.orange)
                        } else {
                            TextField("Speaker", text: $turn.speaker)
                                .textFieldStyle(.roundedBorder)
                                .frame(width: 150)
                            Menu("Assign") {
                                ForEach(transcriptSpeakerOptions, id: \.self) { speaker in
                                    Button(speaker) { turn.speaker = speaker }
                                }
                            }
                            .controlSize(.small)
                        }
                    }
                    TextEditor(text: $turn.text)
                        .font(.system(size: 13))
                        .frame(minHeight: 58)
                        .padding(4)
                        .overlay {
                            RoundedRectangle(cornerRadius: 6)
                                .stroke(Color.secondary.opacity(0.2))
                        }
                }
                .padding(12)
                .background(RoundedRectangle(cornerRadius: 10).fill(Color.secondary.opacity(0.05)))
            }
        }
    }

    private var transcriptSpeakerOptions: [String] {
        let directNames = speakerNames.values.filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
        return Array(Set(transcriptTurns.filter { !$0.isNote }.map(\.speaker) + directNames))
            .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
    }

    private var speakerEditor: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Name speakers")
                .font(.system(size: 18, weight: .semibold))
            Text("These names are saved only for this session and replace anonymous speaker labels in its transcript and summary.")
                .font(.system(size: 12))
                .foregroundStyle(.secondary)
            if speakerLabels.isEmpty {
                Text("No anonymous speakers found in this transcript.")
                    .font(.system(size: 13))
                    .foregroundStyle(.secondary)
            } else {
                Grid(alignment: .leading, horizontalSpacing: 14, verticalSpacing: 10) {
                    ForEach(speakerLabels, id: \.self) { label in
                        GridRow {
                            Text(label)
                                .font(.system(size: 13, weight: .medium))
                            TextField("Name", text: speakerBinding(for: label))
                                .textFieldStyle(.roundedBorder)
                        }
                    }
                }
            }
            HStack {
                Spacer()
                Button("Cancel") { showingSpeakerEditor = false }
                Button("Save", action: saveSpeakerNames)
                    .keyboardShortcut(.defaultAction)
            }
        }
        .padding(22)
        .frame(width: 470)
    }

    private func speakerBinding(for label: String) -> Binding<String> {
        Binding(
            get: { speakerNames[label, default: ""] },
            set: { speakerNames[label] = $0 }
        )
    }

    private func saveSpeakerNames() {
        guard let selected else { return }
        let names = speakerNames.reduce(into: [String: String]()) { result, pair in
            let name = pair.value.trimmingCharacters(in: .whitespacesAndNewlines)
            if !name.isEmpty { result[pair.key] = name }
        }
        let url = selected.url.appendingPathComponent("speaker-names.json")
        if names.isEmpty {
            try? FileManager.default.removeItem(at: url)
        } else if let data = try? JSONEncoder().encode(names) {
            try? data.write(to: url, options: .atomic)
            try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        }
        speakerNames = names
        showingSpeakerEditor = false
        loadText()
    }

    /// The two-part summary format (`=== SHARE BRIEF ===` / `=== FULL RECORD
    /// ===`): split so the brief renders as a plain preformatted block (it's
    /// meant to paste verbatim) and the record as markdown. Falls back to
    /// rendering `fileText` unsplit, exactly as before, when the marker is
    /// absent — legacy summaries and every other file type are unaffected.
    private var summarySplit: (brief: String, record: String)? {
        guard let recordRange = fileText.range(of: "=== FULL RECORD ===") else { return nil }
        var brief = String(fileText[..<recordRange.lowerBound])
        if let briefMarkerRange = brief.range(of: "=== SHARE BRIEF ===") {
            brief = String(brief[briefMarkerRange.upperBound...])
        }
        brief = brief.trimmingCharacters(in: .whitespacesAndNewlines)
        let record = String(fileText[recordRange.upperBound...]).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !brief.isEmpty else { return nil }
        return (brief, record)
    }
}

private struct SessionReadingBackground: View {
    var body: some View {
        Color(nsColor: .textBackgroundColor)
            .overlay(
                LinearGradient(
                    colors: [
                        Color.secondary.opacity(0.018),
                        Color.clear
                    ],
                    startPoint: .top,
                    endPoint: .bottom
                )
            )
    }
}

private struct SessionDocumentSection<Content: View>: View {
    let title: String
    let systemImage: String
    let content: Content

    init(title: String, systemImage: String, @ViewBuilder content: () -> Content) {
        self.title = title
        self.systemImage = systemImage
        self.content = content()
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            Label(title, systemImage: systemImage)
                .font(.system(size: 12, weight: .semibold))
                .foregroundStyle(RTIDesign.Color.textSecondary)
            content
        }
    }
}

private struct SessionTranscriptReader: View {
    let turns: [SessionTranscriptTurn]

    var body: some View {
        if turns.isEmpty {
            Text("No transcript turns found.")
                .font(RTIDesign.Font.body)
                .foregroundStyle(RTIDesign.Color.textSecondary)
        } else {
            LazyVStack(alignment: .leading, spacing: 0) {
                ForEach(Array(turns.enumerated()), id: \.element.id) { index, turn in
                    HStack(alignment: .top, spacing: 18) {
                        HStack(alignment: .firstTextBaseline, spacing: 7) {
                            Circle()
                                .fill(speakerColor(turn.speaker, isNote: turn.isNote))
                                .frame(width: 7, height: 7)
                            VStack(alignment: .leading, spacing: 3) {
                                Text(turn.isNote ? "Note" : turn.speaker)
                                    .font(.system(size: 12, weight: .semibold))
                                    .foregroundStyle(RTIDesign.Color.textSecondary)
                                    .lineLimit(1)
                                Text(turn.timestamp)
                                    .font(.system(size: 10, design: .monospaced))
                                    .foregroundStyle(RTIDesign.Color.textTertiary)
                            }
                        }
                        .frame(width: 118, alignment: .leading)

                        Text(turn.text)
                            .font(.system(size: 14))
                            .foregroundStyle(turn.isNote ? RTIDesign.Color.textSecondary : RTIDesign.Color.textPrimary)
                            .italic(turn.isNote)
                            .lineSpacing(4)
                            .textSelection(.enabled)
                            .fixedSize(horizontal: false, vertical: true)
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.vertical, 15)

                    if index < turns.count - 1 {
                        Divider()
                            .padding(.leading, 136)
                    }
                }
            }
        }
    }

    private func speakerColor(_ speaker: String, isNote: Bool) -> Color {
        if isNote { return .orange }
        let digits = speaker.reversed().prefix { $0.isNumber }.reversed()
        guard let number = Int(String(digits)), !RTIDesign.Color.speakerPalette.isEmpty else {
            return RTIDesign.Color.accent
        }
        return RTIDesign.Color.speakerPalette[(max(number, 1) - 1) % RTIDesign.Color.speakerPalette.count]
    }
}

private struct ArchivedFinding: Identifiable {
    let id = UUID()
    let tag: String
    let timestamp: String
    let headline: String
    var matters: String = ""
    var quote: String?
    var speaker: String?

    static func parse(_ markdown: String) -> [ArchivedFinding] {
        let headlinePattern = #"^- \*\*\[([^\]]+)\]\*\* `([^`]+)` (.+)$"#
        guard let regex = try? NSRegularExpression(pattern: headlinePattern) else { return [] }
        var result: [ArchivedFinding] = []
        var current: ArchivedFinding?

        for line in markdown.components(separatedBy: .newlines) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            let range = NSRange(trimmed.startIndex..., in: trimmed)
            if let match = regex.firstMatch(in: trimmed, range: range),
               let tagRange = Range(match.range(at: 1), in: trimmed),
               let timeRange = Range(match.range(at: 2), in: trimmed),
               let headlineRange = Range(match.range(at: 3), in: trimmed) {
                if let current { result.append(current) }
                current = ArchivedFinding(
                    tag: String(trimmed[tagRange]),
                    timestamp: String(trimmed[timeRange]),
                    headline: String(trimmed[headlineRange])
                )
            } else if trimmed.hasPrefix("- _Why:_ "), current != nil {
                current?.matters = String(trimmed.dropFirst("- _Why:_ ".count))
            } else if trimmed.hasPrefix("- > "), current != nil {
                let evidence = String(trimmed.dropFirst("- > ".count))
                if let split = evidence.range(of: ": ") {
                    current?.speaker = String(evidence[..<split.lowerBound])
                    current?.quote = String(evidence[split.upperBound...])
                } else {
                    current?.quote = evidence
                }
            }
        }

        if let current { result.append(current) }
        return result
    }
}

private struct LiveIntelligenceReader: View {
    let items: [ArchivedFinding]

    var body: some View {
        if items.isEmpty {
            Text("No intelligence items found.")
                .font(RTIDesign.Font.body)
                .foregroundStyle(RTIDesign.Color.textSecondary)
        } else {
            LazyVStack(alignment: .leading, spacing: 0) {
                ForEach(Array(items.enumerated()), id: \.element.id) { index, item in
                    VStack(alignment: .leading, spacing: 10) {
                        HStack(alignment: .firstTextBaseline, spacing: 9) {
                            Label(item.tag, systemImage: icon(for: item.tag))
                                .font(.system(size: 11, weight: .semibold))
                                .foregroundStyle(color(for: item.tag))
                                .padding(.horizontal, 8)
                                .frame(height: 23)
                                .background(
                                    RoundedRectangle(cornerRadius: 7, style: .continuous)
                                        .fill(color(for: item.tag).opacity(0.10))
                                )
                            Text(item.timestamp)
                                .font(.system(size: 10, design: .monospaced))
                                .foregroundStyle(RTIDesign.Color.textTertiary)
                            Spacer(minLength: 0)
                        }

                        Text(item.headline)
                            .font(.system(size: 15, weight: .semibold))
                            .foregroundStyle(RTIDesign.Color.textPrimary)
                            .fixedSize(horizontal: false, vertical: true)

                        if !item.matters.isEmpty {
                            Text(item.matters)
                                .font(.system(size: 13))
                                .foregroundStyle(RTIDesign.Color.textSecondary)
                                .lineSpacing(3)
                                .fixedSize(horizontal: false, vertical: true)
                        }

                        if let quote = item.quote {
                            HStack(alignment: .top, spacing: 9) {
                                Image(systemName: "quote.opening")
                                    .font(.system(size: 10, weight: .semibold))
                                    .foregroundStyle(RTIDesign.Color.accentText)
                                    .padding(.top, 2)
                                Text(([item.speaker, quote].compactMap { $0 }).joined(separator: ": "))
                                    .font(.system(size: 12))
                                    .foregroundStyle(RTIDesign.Color.textSecondary)
                                    .italic()
                                    .lineSpacing(3)
                                    .fixedSize(horizontal: false, vertical: true)
                            }
                            .padding(.horizontal, 12)
                            .padding(.vertical, 10)
                            .background(
                                RoundedRectangle(cornerRadius: 9, style: .continuous)
                                    .fill(RTIDesign.Color.accentBg.opacity(0.55))
                            )
                        }
                    }
                    .padding(.vertical, 17)

                    if index < items.count - 1 {
                        Divider()
                    }
                }
            }
        }
    }

    private func color(for tag: String) -> Color {
        switch tag.lowercased() {
        case "decision": return Color(red: 0.10, green: 0.48, blue: 0.28)
        case "action", "follow-up": return RTIDesign.Color.accentText
        case "open question": return Color(red: 0.45, green: 0.28, blue: 0.68)
        case "risk", "tension", "contradiction": return Color(red: 0.72, green: 0.36, blue: 0.08)
        default: return Color(red: 0.12, green: 0.45, blue: 0.52)
        }
    }

    private func icon(for tag: String) -> String {
        switch tag.lowercased() {
        case "decision": return "checkmark.circle.fill"
        case "action": return "checklist"
        case "open question": return "questionmark.circle"
        case "risk": return "exclamationmark.triangle"
        case "follow-up": return "arrowshape.turn.up.right"
        default: return "lightbulb"
        }
    }
}
