import SwiftUI
import UniformTypeIdentifiers

/// Read-only browser for archived session records (the Markdown folders
/// SessionArchive writes to the vault on stop). Browse and read — never
/// resume: past sessions are vault content, and anything beyond reading
/// (search, analysis, Q&A) is a vault job, not an app feature.
struct SessionsBrowserView: View {
    @State private var sessions: [SessionArchive.ArchivedSession] = []
    @State private var selected: SessionArchive.ArchivedSession?
    @State private var files: [SessionFile] = []
    @State private var selectedFile: SessionFile?
    @State private var fileText: String = ""
    @State private var upgradeStatus: String?
    @State private var upgradeStatusSessionID: URL?
    @State private var upgradingSessionID: URL?
    @State private var pendingUpgradeSession: SessionArchive.ArchivedSession?
    @State private var showingUpgradeProviderChoice = false

    struct SessionFile: Identifiable, Hashable {
        var id: URL { url }
        let url: URL
        let name: String
    }

    /// Preferred reading order when a session folder is opened.
    private static let fileOrder = ["summary.md", "notes.md", "transcript.md", "chat.md", "discussion-guide.md"]

    var body: some View {
        HSplitView {
            sessionList
                .frame(minWidth: 190, idealWidth: 220, maxWidth: 320)

            VStack(alignment: .leading, spacing: 0) {
                if let selected {
                    detailToolbar(for: selected)
                    if let upgradeStatus, upgradeStatusSessionID == selected.id {
                        upgradeStatusLine(upgradeStatus)
                    }
                    Divider()
                    ScrollView {
                        HStack(alignment: .top, spacing: 0) {
                            RTIMarkdown(fileText, style: .panel)
                                .frame(maxWidth: 700, alignment: .leading)
                                .padding(.horizontal, 20)
                                .padding(.vertical, 22)
                            Spacer(minLength: 0)
                        }
                    }
                    .frame(maxWidth: .infinity)
                    .background(SessionReadingBackground())
                } else {
                    emptyState
                }
            }
            .frame(minWidth: 380)
        }
        .onAppear(perform: reload)
        .onChange(of: selected) { _, _ in loadFiles() }
        .onChange(of: selectedFile) { _, _ in loadText() }
        .onReceive(NotificationCenter.default.publisher(for: .rtiOpenSessionInBrowser)) { notif in
            guard let folder = notif.object as? String else { return }
            selectSession(folder: folder)
        }
        .confirmationDialog(
            "Upgrade transcript with",
            isPresented: $showingUpgradeProviderChoice,
            titleVisibility: .visible,
            presenting: pendingUpgradeSession
        ) { session in
            ForEach(upgradeProviderChoices) { provider in
                Button(upgradeProviderButtonTitle(provider)) {
                    startTranscriptUpgrade(for: session, provider: provider)
                }
            }
            Button("Cancel", role: .cancel) {
                pendingUpgradeSession = nil
            }
        } message: { _ in
            Text("Soniox is the default general-purpose file transcript provider. Choose Aliyun when this archived session is Chinese-heavy and you want the upgraded transcript generated by Aliyun.")
        }
    }

    /// Deep-link target for the "summary ready" notification and the overlay's
    /// "Notes ready" control: refresh the list, select the matching session
    /// folder, and land on its summary. Re-selecting the same session still
    /// snaps the reader back to summary.md (loadFiles picks files.first).
    private func selectSession(folder: String) {
        sessions = SessionArchive.recentSessions(limit: 100)
        guard let match = sessions.first(where: { $0.url.lastPathComponent == folder }) else { return }
        selected = match
        loadFiles()
    }

    // MARK: - Session list

    private var sessionList: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 18) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Sessions")
                        .font(.system(size: 24, weight: .semibold))
                    Text("Read saved meeting records and open the files RTI wrote on stop.")
                        .font(.system(size: 12))
                        .foregroundStyle(.secondary)
                }
                .padding(.horizontal, 18)
                .padding(.top, 18)

                ForEach(groupedSessions, id: \.label) { group in
                    VStack(alignment: .leading, spacing: 8) {
                        Text(group.label.uppercased())
                            .font(.system(size: 11, weight: .bold))
                            .tracking(0.8)
                            .foregroundStyle(.secondary)
                            .padding(.horizontal, 18)
                        VStack(spacing: 8) {
                            ForEach(group.sessions) { session in
                                sessionRow(session)
                            }
                        }
                        .padding(.horizontal, 12)
                    }
                }
            }
        }
        .scrollContentBackground(.hidden)
        .background(.thinMaterial)
    }

    /// One row: AI-generated title as the primary label, the start time as a
    /// quiet secondary. No redundant clock icon — every row is a past session,
    /// so the icon was just clutter. A small dot marks sessions whose
    /// auto-summary hasn't landed yet (still "Untitled").
    private func sessionRow(_ session: SessionArchive.ArchivedSession) -> some View {
        Button {
            selected = session
        } label: {
            HStack(alignment: .center, spacing: 10) {
                VStack(alignment: .leading, spacing: 3) {
                    Text(session.title ?? "Untitled session")
                        .font(.system(size: 13, weight: .medium))
                        .lineLimit(2)
                        .foregroundStyle(session.title == nil ? .secondary : .primary)
                    HStack(spacing: 6) {
                        Text(timeString(for: session))
                            .font(.system(size: 10, design: .monospaced))
                            .foregroundStyle(.tertiary)
                        if session.title == nil {
                            Circle()
                                .fill(Color.secondary.opacity(0.5))
                                .frame(width: 4, height: 4)
                                .help("No summary yet — the title appears once the end-of-session summary finishes.")
                        }
                    }
                }
                Spacer(minLength: 0)
            }
            .padding(.horizontal, 14)
            .padding(.vertical, 11)
            .background(
                RoundedRectangle(cornerRadius: 16, style: .continuous)
                    .fill(selected == session ? Color.black.opacity(0.07) : Color.clear)
            )
        }
        .buttonStyle(.plain)
    }

    // MARK: - Detail toolbar

    /// File picker (summary / notes / transcript / …) aligned with the
    /// reading column, with contextual actions trailing in the titlebar-style
    /// header.
    @ViewBuilder
    private func detailToolbar(for session: SessionArchive.ArchivedSession) -> some View {
        HStack(alignment: .center, spacing: 12) {
            Picker("", selection: $selectedFile) {
                ForEach(files) { file in
                    Text(file.name).tag(Optional(file))
                }
            }
            .pickerStyle(.segmented)
            .labelsHidden()
            .frame(
                minWidth: min(CGFloat(files.count) * 74, 180),
                idealWidth: min(CGFloat(files.count) * 90, 480),
                maxWidth: min(CGFloat(files.count) * 104, 560),
                alignment: .leading
            )

            Spacer(minLength: 12)

            Button {
                NSPasteboard.copyMarkdownRich(fileText)
            } label: {
                Label("Copy", systemImage: "doc.on.doc")
            }
            .buttonStyle(.bordered)
            .controlSize(.small)
            .help("Copy as Markdown")
            .disabled(fileText.isEmpty)

            Button {
                promptTranscriptUpgrade(for: session)
            } label: {
                Label(upgradingSessionID == session.id ? "Upgrading" : "Upgrade Transcript", systemImage: "waveform.badge.magnifyingglass")
            }
            .buttonStyle(.bordered)
            .controlSize(.small)
            .disabled(upgradingSessionID != nil || !canUpgrade(session))
            .help(canUpgrade(session) ? "Run the configured async transcript provider over this session's retained audio." : "No retained session audio was found.")

            Menu {
                Button("Save as Markdown…") { exportMarkdown() }
                Button("Save as PDF…") { exportPDF() }
                Divider()
                Button("Reveal in Finder") { NSWorkspace.shared.open(session.url) }
            } label: {
                Image(systemName: "square.and.arrow.up")
            }
            .menuStyle(.borderlessButton)
            .frame(width: 34)
            .help("Export or reveal this session")
        }
        .frame(height: 44)
        .padding(.horizontal, 20)
        .background(.bar)
    }

    private func upgradeStatusLine(_ text: String) -> some View {
        HStack(spacing: 8) {
            if upgradingSessionID == upgradeStatusSessionID {
                ProgressView()
                    .controlSize(.small)
                    .scaleEffect(0.7)
            }
            Text(text)
                .font(.system(size: 11))
                .foregroundStyle(.secondary)
                .lineLimit(3)
                .fixedSize(horizontal: false, vertical: true)
            Spacer(minLength: 0)
        }
        .frame(minHeight: 28)
        .padding(.horizontal, 20)
        .padding(.vertical, 5)
        .background(.bar)
    }

    private var emptyState: some View {
        VStack(spacing: 8) {
            Image(systemName: "tray")
                .font(.system(size: 30))
                .foregroundStyle(.tertiary)
            Text(sessions.isEmpty ? "No saved sessions yet" : "Select a session")
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(.secondary)
            if !sessions.isEmpty {
                Text("Sessions appear here once they're saved on stop.")
                    .font(.system(size: 11))
                    .foregroundStyle(.tertiary)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: - Date grouping

    /// Buckets sessions into native macOS-style date sections: Today,
    /// Yesterday, This Week, then one section per older month
    /// ("June 2026"). Sessions with an unparseable folder stamp fall into
    /// "Earlier". Removes the repetitive month/day text from individual rows
    /// — the section header carries the date, the row carries just the time.
    private var groupedSessions: [(label: String, sessions: [SessionArchive.ArchivedSession])] {
        let cal = Calendar.current
        let now = Date()
        var today: [SessionArchive.ArchivedSession] = []
        var yesterday: [SessionArchive.ArchivedSession] = []
        var thisWeek: [SessionArchive.ArchivedSession] = []
        var byMonth: [(label: String, key: String, sessions: [SessionArchive.ArchivedSession])] = []
        var earlier: [SessionArchive.ArchivedSession] = []

        for session in sessions {
            guard let date = session.date else {
                earlier.append(session)
                continue
            }
            if cal.isDateInToday(date) {
                today.append(session)
            } else if cal.isDateInYesterday(date) {
                yesterday.append(session)
            } else if let days = cal.dateComponents([.day], from: date, to: now).day, days < 7 {
                thisWeek.append(session)
            } else {
                let key = monthKey(date)
                let label = monthLabel(date)
                if let idx = byMonth.firstIndex(where: { $0.key == key }) {
                    byMonth[idx].sessions.append(session)
                } else {
                    byMonth.append((label, key, [session]))
                }
            }
        }

        var out: [(label: String, sessions: [SessionArchive.ArchivedSession])] = []
        if !today.isEmpty { out.append(("Today", today)) }
        if !yesterday.isEmpty { out.append(("Yesterday", yesterday)) }
        if !thisWeek.isEmpty { out.append(("This Week", thisWeek)) }
        // Months are newest-first because `sessions` is newest-first.
        for m in byMonth.sorted(by: { $0.key > $1.key }) {
            out.append((m.label, m.sessions))
        }
        if !earlier.isEmpty { out.append(("Earlier", earlier)) }
        return out
    }

    /// "16:13" for the row's quiet secondary text. Falls back to the pretty
    /// name when the folder stamp can't be parsed.
    private func timeString(for session: SessionArchive.ArchivedSession) -> String {
        guard let date = session.date else { return session.displayName }
        return Self.rowTimeStamp.string(from: date)
    }

    private static let rowTimeStamp: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "HH:mm"
        return f
    }()

    private func monthKey(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM"
        return f.string(from: date)
    }

    private func monthLabel(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateFormat = "MMMM yyyy"
        return f.string(from: date)
    }

    // MARK: - Loading

    private func reload() {
        sessions = SessionArchive.recentSessions(limit: 100)
        if selected == nil { selected = sessions.first }
    }

    private func loadFiles() {
        guard let selected else { files = []; selectedFile = nil; return }
        let present = (try? FileManager.default.contentsOfDirectory(at: selected.url, includingPropertiesForKeys: nil)) ?? []
        let byName = Dictionary(uniqueKeysWithValues: present.map { ($0.lastPathComponent, $0) })
        files = Self.fileOrder.compactMap { name in
            byName[name].map { SessionFile(url: $0, name: String(name.dropLast(3))) }
        }
        selectedFile = files.first
    }

    private func canUpgrade(_ session: SessionArchive.ArchivedSession) -> Bool {
        !TranscriptUpgradeService.audioInputs(in: session.url).isEmpty
    }

    private var upgradeProviderChoices: [AsyncTranscriptProviderOption] {
        let active = AsyncTranscriptProviders.active
        return [active] + AsyncTranscriptProviders.all.filter { $0.id != active.id }
    }

    private func upgradeProviderButtonTitle(_ provider: AsyncTranscriptProviderOption) -> String {
        if provider.id == AsyncTranscriptProviders.aliyun.id {
            return "Aliyun (Chinese-heavy)"
        }
        if provider.id == AsyncTranscriptProviders.soniox.id {
            return provider.id == AsyncTranscriptProviders.active.id ? "Soniox (default)" : "Soniox"
        }
        return provider.displayName
    }

    private func promptTranscriptUpgrade(for session: SessionArchive.ArchivedSession) {
        pendingUpgradeSession = session
        showingUpgradeProviderChoice = true
    }

    private func startTranscriptUpgrade(for session: SessionArchive.ArchivedSession, provider: AsyncTranscriptProviderOption) {
        pendingUpgradeSession = nil
        upgradingSessionID = session.id
        upgradeStatusSessionID = session.id
        upgradeStatus = "Starting transcript upgrade with \(provider.displayName)…"
        Task {
            do {
                let result = try await TranscriptUpgradeService.upgrade(session: session, provider: provider) { progress in
                    Task { @MainActor in
                        upgradeStatusSessionID = session.id
                        upgradeStatus = progress.message
                        if progress.isTerminal { upgradingSessionID = nil }
                    }
                }
                await MainActor.run {
                    upgradeStatus = result.summaryURL == nil
                        ? "Transcript upgraded with \(result.provider); summary regeneration failed."
                        : "Transcript upgraded with \(result.provider); summary regenerated."
                    upgradeStatusSessionID = session.id
                    upgradingSessionID = nil
                    reload()
                    selected = sessions.first(where: { $0.id == session.id }) ?? selected
                    loadFiles()
                    selectedFile = files.first(where: { $0.name == "transcript" }) ?? files.first
                }
            } catch {
                await MainActor.run {
                    upgradeStatus = (error as? LocalizedError)?.errorDescription ?? error.localizedDescription
                    upgradeStatusSessionID = session.id
                    upgradingSessionID = nil
                }
            }
        }
    }

    private func exportMarkdown() {
        guard let selectedFile, let selected else { return }
        let panel = NSSavePanel()
        panel.nameFieldStringValue = "rti-\(selectedFile.name)-\(selected.displayName.replacingOccurrences(of: " · ", with: "-").replacingOccurrences(of: ":", with: "")).md"
        panel.allowedContentTypes = [UTType(filenameExtension: "md") ?? .plainText]
        let content = fileText
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            try? content.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    /// Render the markdown to a paginated PDF via NSAttributedString printing.
    private func exportPDF() {
        guard let selectedFile else { return }
        let panel = NSSavePanel()
        panel.nameFieldStringValue = panelBaseName(selectedFile) + ".pdf"
        panel.allowedContentTypes = [.pdf]
        let content = fileText
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            let attributed = (try? NSAttributedString(
                markdown: content,
                options: .init(interpretedSyntax: .inlineOnlyPreservingWhitespace)
            )) ?? NSAttributedString(string: content)
            let textView = NSTextView(frame: NSRect(x: 0, y: 0, width: 540, height: 720))
            textView.textStorage?.setAttributedString(attributed)
            textView.font = .systemFont(ofSize: 11)
            let printInfo = NSPrintInfo()
            printInfo.jobDisposition = .save
            printInfo.dictionary()[NSPrintInfo.AttributeKey.jobSavingURL] = url
            printInfo.topMargin = 36; printInfo.bottomMargin = 36
            printInfo.leftMargin = 36; printInfo.rightMargin = 36
            let op = NSPrintOperation(view: textView, printInfo: printInfo)
            op.showsPrintPanel = false
            op.showsProgressPanel = false
            op.run()
        }
    }

    private func panelBaseName(_ file: SessionFile) -> String {
        let stamp = selected?.displayName
            .replacingOccurrences(of: " · ", with: "-")
            .replacingOccurrences(of: ":", with: "") ?? "session"
        return "rti-\(file.name)-\(stamp)"
    }

    private func loadText() {
        guard let selectedFile else { fileText = ""; return }
        var text = (try? String(contentsOf: selectedFile.url, encoding: .utf8)) ?? "(couldn't read file)"
        // Hide the machine-facing frontmatter block from the reading view.
        if text.hasPrefix("---"), let end = text.range(of: "\n---\n") {
            text = String(text[end.upperBound...])
        }
        fileText = text
    }
}

private struct SessionReadingBackground: View {
    var body: some View {
        Color(nsColor: .textBackgroundColor)
            .overlay(
                LinearGradient(
                    colors: [
                        Color.secondary.opacity(0.018),
                        Color.clear
                    ],
                    startPoint: .top,
                    endPoint: .bottom
                )
            )
    }
}
