import AppKit

extension NSPasteboard {
    /// Clear the general pasteboard and set a single string, with the
    /// transient markers (below). Everything RTI copies is text it made (an
    /// answer, a transcript, a source list), so clipboard managers are told
    /// not to keep it. Named `copyString` rather than `copy` to avoid
    /// colliding with NSObject's Obj-C `copy(_:)` selector.
    static func copyString(_ text: String) {
        writeTransient(text, to: .general)
    }

    /// The markers clipboard managers honour (nspasteboard.org): transient
    /// means "do not record", auto-generated means "the app wrote this, not
    /// the user". Same pair as Quick Launch's `writeTransientString`.
    static let transientMarkers: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Writes `text` with the transient markers. Each marker carries empty
    /// data, so it is on the pasteboard whichever way a manager checks.
    static func writeTransient(_ text: String, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        pasteboard.declareTypes([.string] + transientMarkers, owner: nil)
        pasteboard.setString(text, forType: .string)
        for marker in transientMarkers {
            pasteboard.setData(Data(), forType: marker)
        }
    }
}
